stages:

  download:
    cmd:
    - curl -O ${dataset.url}
    - unzip fra-eng.zip
    - rm _about.txt fra-eng.zip
    deps:
    - ${dataset.url}
    outs:
    - ${dataset.data_path}

  train:
    cmd: python train.py
    deps:
    - ${dataset.data_path}
    - train.py
    params:
    - params.yaml:
    outs:
    - model
    - results/artifacts
    - results/metrics.json:
        cache: false
    - results/plots:
        cache: false

params:
- results/params.yaml
metrics:
- results/metrics.json
plots:
- results/plots/metrics:
    x: step
artifacts:
  best:
    path: results/artifacts/epoch=1-step=314.ckpt
    type: model
