model:
  batch_size: 512
  latent_dim: 8
  duration: 00:00:30:00
  max_epochs: 2
  optim:
    lr: 0.01
dataset:
  num_samples: 100000
  data_path: fra.txt
  url: http://www.manythings.org/anki/fra-eng.zip
seed: 423
